version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm i
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "testing stuff"
      - run: npm i
      - run: npm test
  hithere:
    docker:
      - image: circleci/node:8.9
    steps:
    - checkout
    - run: echo "Hello there, this is useless, well, it's not running anything"
workflows:
  version: 2
  build_test_and_lint:
    jobs:
      - build
      - hithere
      - test:
          requires:
            - hithere
